<?php
/**
*   Shopware Theme - Simple Shopware theme with backend configurations options
*   Copyright (C) 2020, JuanK
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

namespace JkTheme;

use Shopware\Components\Plugin;
use JkTheme\Models\Theme;
use Doctrine\ORM\Tools\SchemaTool;
use Shopware\Components\Model\ModelManager;
use Shopware\Components\Plugin\Context\ActivateContext;
use Shopware\Components\Plugin\Context\InstallContext;
use Shopware\Components\Plugin\Context\UninstallContext;
use Shopware\Components\Plugin\Context\UpdateContext;
use JkTheme\Services\UninstallHelper as Helper;

class JkTheme extends Plugin
{
  /**
  * {@inheritdoc}
  */
  public function install(InstallContext $context)
  {
    $this->createDatabase();
    parent::install($context); // TODO: Change the autogenerated stub
  }

  public function update(UpdateContext $context)
  {
    parent::update($context); // TODO: Change the autogenerated stub
  }

  /**
  * {@inheritdoc}
  */
  public function activate(ActivateContext $activateContext)
  {
    $activateContext->scheduleClearCache(ActivateContext::CACHE_LIST_DEFAULT);
  }

  /**
  * {@inheritdoc}
  */
  public function uninstall(UninstallContext $uninstallContext)
  {
    //This part helps to set the theme to Responsive in case that Theme 'JkTheme'
    //was assigned to a one or more shops
    //the result is that all those shops will have the Responsive Theme
    $helper = new Helper();
    $helper->setResponsiveTheme();

    if (!$uninstallContext->keepUserData()) {
      $this->removeDatabase();

    }
  }
  /**
  * Create the new table called 's_plugin_jk_theme' in the database.
  */
  private function createDatabase()
  {
    $modelManager = $this->container->get('models');
    $tool         = new SchemaTool($modelManager);

    $classes = $this->getClasses($modelManager);

    try {
      $tool->dropSchema($classes);
    } catch (\Exception $e) {
    }
    $tool->createSchema($classes); // make sure use the save mode
  }

  /**
  * Drop table called 's_plugin_jk_theme' from the database.
  */
  private function removeDatabase()
  {
    $modelManager = $this->container->get('models');
    $tool         = new SchemaTool($modelManager);

    $classes = $this->getClasses($modelManager);

    $tool->dropSchema($classes);
  }

  /**
  * @param ModelManager $modelManager
  * @return array
  */
  private function getClasses(ModelManager $modelManager)
  {
    return [
      $modelManager->getClassMetadata(Theme::class),
    ];
  }



}
